# Generated by Django 6.0 on 2025-12-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skilloryx", "0002_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
