# Generated by Django 6.0 on 2025-12-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skilloryx", "0003_delete_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
